package constants;

public enum Commands {
	C_NEW, C_EDIT, C_EXIT, C_SPANISH, C_ENGLISH, C_HOME, C_DELETE,C_REFRESH, C_ADD, C_CANCEL,
	
	
	C_SHOW_FIRST_REPORT,
	C_SHOW_SECOND_REPORT,
	C_SHOW_THREE_REPORT,
	C_SHOW_FOUR_REPORT,
	C_SHOW_FIVE_REPORT,
	C_SHOW_SIX_REPORT,
	C_SHOW_SEVEN_REPORT,
	C_SHOW_EIGTH_REPORT,
	C_SHOW_NINE_REPORT,
	C_SHOW_TEN_REPORT
}
